name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: Build CI container
    runs-on: ubuntu-latest
    steps:
      - name: "Install Build X"
        uses: docker/setup-buildx-action@v1

      - name: "Build docker image - production"
        uses: docker/build-push-action@v2
        with:
          target: production
          tags: ghcr.io/bendavies/docker-build-composer-cache:production
          push: false
          load: true
          cache-from: type=gha,scope=production
          cache-to: type=gha,mode=max,scope=production

      - name: "Build docker image - development"
        uses: docker/build-push-action@v2
        with:
          target: development
          tags: ghcr.io/bendavies/docker-build-composer-cache:developement
          push: false
          load: true
          cache-from: |
            type=gha,scope=production
            type=gha,scope=development
          cache-to: type=gha,mode=max,scope=development